// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_protected_middleware from "./routes/api/(protected)/_middleware.ts";
import * as $api_protected_archive_archive_id_bill from "./routes/api/(protected)/archive/[archive_id]/bill.tsx";
import * as $api_protected_archive_archive_id_index from "./routes/api/(protected)/archive/[archive_id]/index.tsx";
import * as $api_protected_bill_bill_id_archive from "./routes/api/(protected)/bill/[bill_id]/archive.ts";
import * as $api_protected_bill_bill_id_invoice from "./routes/api/(protected)/bill/[bill_id]/invoice.ts";
import * as $api_protected_bill_bill_id_payments_images from "./routes/api/(protected)/bill/[bill_id]/payments/images.ts";
import * as $api_protected_bill_bill_id_payments_index from "./routes/api/(protected)/bill/[bill_id]/payments/index.ts";
import * as $api_protected_bill_index from "./routes/api/(protected)/bill/index.ts";
import * as $api_protected_bill_invoices from "./routes/api/(protected)/bill/invoices.ts";
import * as $api_protected_vendor_cached_middleware from "./routes/api/(protected)/vendor/(cached)/_middleware.ts";
import * as $api_protected_vendor_cached_index from "./routes/api/(protected)/vendor/(cached)/index.ts";
import * as $api_protected_vendor_vendor_id_accounts from "./routes/api/(protected)/vendor/[vendor_id]/accounts.ts";
import * as $auth_verify from "./routes/auth/verify.tsx";
import * as $dashboard_layout from "./routes/dashboard/_layout.tsx";
import * as $dashboard_middleware from "./routes/dashboard/_middleware.ts";
import * as $dashboard_archive_bills_archive_id_ from "./routes/dashboard/archive-bills/[archive_id].tsx";
import * as $dashboard_archive_bills_index from "./routes/dashboard/archive-bills/index.tsx";
import * as $dashboard_bills_id_ from "./routes/dashboard/bills/[id].tsx";
import * as $dashboard_bills_create from "./routes/dashboard/bills/create.tsx";
import * as $dashboard_bills_index from "./routes/dashboard/bills/index.tsx";
import * as $dashboard_companies_company_id_ from "./routes/dashboard/companies/[company_id].tsx";
import * as $dashboard_companies_create from "./routes/dashboard/companies/create.tsx";
import * as $dashboard_companies_index from "./routes/dashboard/companies/index.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_payments_create from "./routes/dashboard/payments/create.tsx";
import * as $dashboard_payments_index from "./routes/dashboard/payments/index.tsx";
import * as $dashboard_vendors_id_ from "./routes/dashboard/vendors/[id].tsx";
import * as $dashboard_vendors_create from "./routes/dashboard/vendors/create.tsx";
import * as $dashboard_vendors_index from "./routes/dashboard/vendors/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $profile_layout from "./routes/profile/_layout.tsx";
import * as $profile_middleware from "./routes/profile/_middleware.tsx";
import * as $profile_index from "./routes/profile/index.tsx";
import * as $Combobox from "./islands/Combobox.tsx";
import * as $dashboard_archive_bills_ArchiveBillActions from "./islands/dashboard/archive-bills/ArchiveBillActions.tsx";
import * as $dashboard_archive_bills_ArchiveBillsTableActions from "./islands/dashboard/archive-bills/ArchiveBillsTableActions.tsx";
import * as $dashboard_bills_AddBillPayment from "./islands/dashboard/bills/AddBillPayment.tsx";
import * as $dashboard_bills_CreateBillForm from "./islands/dashboard/bills/CreateBillForm.tsx";
import * as $dashboard_bills_Invoices from "./islands/dashboard/bills/Invoices.tsx";
import * as $dashboard_bills_MoveToArchiveDialog from "./islands/dashboard/bills/MoveToArchiveDialog.tsx";
import * as $dashboard_bills_Pagination from "./islands/dashboard/bills/Pagination.tsx";
import * as $dashboard_bills_PaymentsTable from "./islands/dashboard/bills/PaymentsTable.tsx";
import * as $dashboard_bills_file_input from "./islands/dashboard/bills/file-input.tsx";
import * as $dashboard_create_AddAccountForm from "./islands/dashboard/create/AddAccountForm.tsx";
import * as $dashboard_vendors_AddVendorAccountModal from "./islands/dashboard/vendors/AddVendorAccountModal.tsx";
import * as $dashboard_vendors_VendorAccountTable from "./islands/dashboard/vendors/VendorAccountTable.tsx";
import * as $dashboard_vendors_VendorSearchbox from "./islands/dashboard/vendors/VendorSearchbox.tsx";
import * as $dashboard_vendors_VendorsTable from "./islands/dashboard/vendors/VendorsTable.tsx";
import * as $dashboard_vendors_vendors_data from "./islands/dashboard/vendors/vendors-data.tsx";
import * as $dashboard_vendors_vendors_grid from "./islands/dashboard/vendors/vendors-grid.tsx";
import * as $molecules_AccountForm from "./islands/molecules/AccountForm.tsx";
import * as $molecules_display_preference from "./islands/molecules/display-preference.tsx";
import * as $molecules_profile_dropdown from "./islands/molecules/profile-dropdown.tsx";
import * as $organisms_FileUpload from "./islands/organisms/FileUpload.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/_layout.tsx": $_layout,
		"./routes/api/(protected)/_middleware.ts": $api_protected_middleware,
		"./routes/api/(protected)/archive/[archive_id]/bill.tsx":
			$api_protected_archive_archive_id_bill,
		"./routes/api/(protected)/archive/[archive_id]/index.tsx":
			$api_protected_archive_archive_id_index,
		"./routes/api/(protected)/bill/[bill_id]/archive.ts":
			$api_protected_bill_bill_id_archive,
		"./routes/api/(protected)/bill/[bill_id]/invoice.ts":
			$api_protected_bill_bill_id_invoice,
		"./routes/api/(protected)/bill/[bill_id]/payments/images.ts":
			$api_protected_bill_bill_id_payments_images,
		"./routes/api/(protected)/bill/[bill_id]/payments/index.ts":
			$api_protected_bill_bill_id_payments_index,
		"./routes/api/(protected)/bill/index.ts": $api_protected_bill_index,
		"./routes/api/(protected)/bill/invoices.ts": $api_protected_bill_invoices,
		"./routes/api/(protected)/vendor/(cached)/_middleware.ts":
			$api_protected_vendor_cached_middleware,
		"./routes/api/(protected)/vendor/(cached)/index.ts":
			$api_protected_vendor_cached_index,
		"./routes/api/(protected)/vendor/[vendor_id]/accounts.ts":
			$api_protected_vendor_vendor_id_accounts,
		"./routes/auth/verify.tsx": $auth_verify,
		"./routes/dashboard/_layout.tsx": $dashboard_layout,
		"./routes/dashboard/_middleware.ts": $dashboard_middleware,
		"./routes/dashboard/archive-bills/[archive_id].tsx":
			$dashboard_archive_bills_archive_id_,
		"./routes/dashboard/archive-bills/index.tsx":
			$dashboard_archive_bills_index,
		"./routes/dashboard/bills/[id].tsx": $dashboard_bills_id_,
		"./routes/dashboard/bills/create.tsx": $dashboard_bills_create,
		"./routes/dashboard/bills/index.tsx": $dashboard_bills_index,
		"./routes/dashboard/companies/[company_id].tsx":
			$dashboard_companies_company_id_,
		"./routes/dashboard/companies/create.tsx": $dashboard_companies_create,
		"./routes/dashboard/companies/index.tsx": $dashboard_companies_index,
		"./routes/dashboard/index.tsx": $dashboard_index,
		"./routes/dashboard/payments/create.tsx": $dashboard_payments_create,
		"./routes/dashboard/payments/index.tsx": $dashboard_payments_index,
		"./routes/dashboard/vendors/[id].tsx": $dashboard_vendors_id_,
		"./routes/dashboard/vendors/create.tsx": $dashboard_vendors_create,
		"./routes/dashboard/vendors/index.tsx": $dashboard_vendors_index,
		"./routes/index.tsx": $index,
		"./routes/logout.tsx": $logout,
		"./routes/profile/_layout.tsx": $profile_layout,
		"./routes/profile/_middleware.tsx": $profile_middleware,
		"./routes/profile/index.tsx": $profile_index,
	},
	islands: {
		"./islands/Combobox.tsx": $Combobox,
		"./islands/dashboard/archive-bills/ArchiveBillActions.tsx":
			$dashboard_archive_bills_ArchiveBillActions,
		"./islands/dashboard/archive-bills/ArchiveBillsTableActions.tsx":
			$dashboard_archive_bills_ArchiveBillsTableActions,
		"./islands/dashboard/bills/AddBillPayment.tsx":
			$dashboard_bills_AddBillPayment,
		"./islands/dashboard/bills/CreateBillForm.tsx":
			$dashboard_bills_CreateBillForm,
		"./islands/dashboard/bills/Invoices.tsx": $dashboard_bills_Invoices,
		"./islands/dashboard/bills/MoveToArchiveDialog.tsx":
			$dashboard_bills_MoveToArchiveDialog,
		"./islands/dashboard/bills/Pagination.tsx": $dashboard_bills_Pagination,
		"./islands/dashboard/bills/PaymentsTable.tsx":
			$dashboard_bills_PaymentsTable,
		"./islands/dashboard/bills/file-input.tsx": $dashboard_bills_file_input,
		"./islands/dashboard/create/AddAccountForm.tsx":
			$dashboard_create_AddAccountForm,
		"./islands/dashboard/vendors/AddVendorAccountModal.tsx":
			$dashboard_vendors_AddVendorAccountModal,
		"./islands/dashboard/vendors/VendorAccountTable.tsx":
			$dashboard_vendors_VendorAccountTable,
		"./islands/dashboard/vendors/VendorSearchbox.tsx":
			$dashboard_vendors_VendorSearchbox,
		"./islands/dashboard/vendors/VendorsTable.tsx":
			$dashboard_vendors_VendorsTable,
		"./islands/dashboard/vendors/vendors-data.tsx":
			$dashboard_vendors_vendors_data,
		"./islands/dashboard/vendors/vendors-grid.tsx":
			$dashboard_vendors_vendors_grid,
		"./islands/molecules/AccountForm.tsx": $molecules_AccountForm,
		"./islands/molecules/display-preference.tsx": $molecules_display_preference,
		"./islands/molecules/profile-dropdown.tsx": $molecules_profile_dropdown,
		"./islands/organisms/FileUpload.tsx": $organisms_FileUpload,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
