import { type Config } from "tailwindcss";

export default {
	content: ["{routes,islands,components}/**/*.{ts,tsx}"],
	theme: {
		extend: {
			colors: {
				primary: "#745B0B",
				surfaceTint: "#745B0B",
				onPrimary: "#FFFFFF",
				primaryContainer: "#FFDF92",
				onPrimaryContainer: "#241A00",
				secondary: "#6A5D3F",
				onSecondary: "#FFFFFF",
				secondaryContainer: "#F3E1BB",
				onSecondaryContainer: "#231A04",
				tertiary: "#486549",
				onTertiary: "#FFFFFF",
				tertiaryContainer: "#C9EBC7",
				onTertiaryContainer: "#04210B",
				error: "#BA1A1A",
				onError: "#FFFFFF",
				errorContainer: "#FFDAD6",
				onErrorContainer: "#410002",
				background: "#FFF8F1",
				onBackground: "#1F1B13",
				surface: "#FFF8F1",
				onSurface: "#1F1B13",
				surfaceVariant: "#ECE1CF",
				onSurfaceVariant: "#4C4639",
				outline: "#7E7667",
				outlineVariant: "#CFC5B4",
				shadow: "#000000",
				scrim: "#000000",
				inverseSurface: "#343027",
				inverseOnSurface: "#F9F0E2",
				inversePrimary: "#E5C36C",
				primaryFixed: "#FFDF92",
				onPrimaryFixed: "#241A00",
				primaryFixedDim: "#E5C36C",
				onPrimaryFixedVariant: "#594400",
				secondaryFixed: "#F3E1BB",
				onSecondaryFixed: "#231A04",
				secondaryFixedDim: "#D6C5A0",
				onSecondaryFixedVariant: "#51462A",
				tertiaryFixed: "#C9EBC7",
				onTertiaryFixed: "#04210B",
				tertiaryFixedDim: "#AECFAC",
				onTertiaryFixedVariant: "#314D33",
				surfaceDim: "#E2D9CC",
				surfaceBright: "#FFF8F1",
				surfaceContainerLowest: "#FFFFFF",
				surfaceContainerLow: "#FCF2E5",
				surfaceContainer: "#F6EDDF",
				surfaceContainerHigh: "#F0E7D9",
				surfaceContainerHighest: "#EAE1D4",
			},
			fontSize: {
				"display": "96px",
				"size1": "72px",
				"size2": "64px",
				"size3": "48px",
				"size4": "40px",
				"size5": "32px",
				"size6": "24px",
				"subhead-large": "20px",
				"subhead-medium": "16px",
			},
		},
	},
} satisfies Config;
