name: Deploy
on:
  release:
    types:
      - published


env:
  JWT_SECRET: temp
  RESEND_API_KEY: re_123545
  AWS_ACCESS_KEY_ID: "DUMMY"
  AWS_SECRET_ACCESS_KEY: "DUMMY"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: $GITHUB_REF

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "myledger"
          entrypoint: "main.ts"
          root: "."
